using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ProjectEuler44
{
    /*
     * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

     */
    class Program
    {
        static void Main(string[] args)
        {
            HashSet<int> pentNumbers = new HashSet<int>();
            for (int n = 1; n < 10000; n++)
            {
                int number = 3*n;
                number--;
                number *= n;
                number /= 2;
                pentNumbers.Add(number);
            }

            int diff = 0;
            int sum = 0;

            foreach (int a in pentNumbers)
            {
                foreach (int b in pentNumbers)
                {
                    if (a <= b)
                    {
                        continue;
                    }
                    diff = a - b;
                    sum = a + b;
                    if (pentNumbers.Contains(sum) && pentNumbers.Contains(diff))
                    {
                        Console.WriteLine(a + " : " + b);
                    }
                }
            }

        }
    }
}
