using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

 */
namespace ProjectEuler45
{
    class Program
    {
        static void Main(string[] args)
        {
            for (long i = 2; i < 1000000; i++)
            {
                long triangularNumber = (i * (i + 1))/2;
                if (isHexagonal(triangularNumber) && isPentagonal(triangularNumber))
                {
                    Console.WriteLine(triangularNumber);
                    if (triangularNumber > 40755)
                    {
                        break;
                    }
                }

            }
        }

        static bool isHexagonal(long number)
        {
            double temp = 0.0;
            temp = Math.Sqrt(1 + 8 * number);
            temp += 1;
            temp /= 4;
            temp = temp % 1;
            if (temp == 0)
            {
                return true;
            }
            return false;
        }

        static bool isPentagonal(long number)
        {
            double temp = 0.0;
            temp = Math.Sqrt(1 + 24 * number);
            temp += 1;
            temp /= 6;
            temp = temp % 1;
            if (temp == 0)
            {
                return true;
            }
            return false;
        }


    }
}
